[server]
# Whether to show a terminal prompt for the user's email address when
# they run Streamlit (locally) for the first time. 
# Disable this prompt for workshop participants, as they seem to dislike
# it and it seems unnecessary.
showEmailPrompt = false